---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflared-credentials
spec:
  encryptedData:
    credentials.json: AgAVZEorlldIojz8G7AHfVTfNfYk0MwucSrU4TjI/wB1PbOiz4w6m45i4Hn1vA92ICLHhwtOnvnWOzwmgLjSR1ET6hjrBy87wiQX50MYERGYyo5gpNzLapr+lXQBOUsXmPlkZHMDkMvk6bx058n5wvNDP2ooylO6MW9MePcT8eHonD0cdyTWjV/AL3ORkky4CxqSX9R1k6fX5bW2BpfE7ab4486l5kW6JWZpPeAxmVke64A1zc+xsEStzG4lCqQWtVSa1hy231LNXfzWsdB8Nwk9oXzRWEzdNDRBDQQYBs57we4hQs7W+E3ZQmkwbZzFgnUzZyk5JoCiYoAEN/IVDiqw2zSsv+35WTwogeNu/fQ/2HHon2xTjVv5BRAkDqELUXwqk8UJa/eQqAGUQNLQLbr0Xe2ILZ80B/ZJ6dtc1ZMP6MI9udD8/yCb/arVGLiPlWEe5r0VL5bOapKzga7tF20s4yWAjQfJEPkM429OAWp6RFFMsVkyFSDozIW2Nlt/sA2yqVtqPqDdIzWUvGA8erR7QbeNGBQdK9YW9lxEHgpZWT4pzAxjCw2dqEEE9GicsXgk0vwursPJwJ9oGno0bTHlkTFhBy9/bqxQQVDtimhHmdUHoQLHHW+SayDr7PGnSbdXkznOpZEVYJExElXqSmwW2Arh9YDzTIC7XqefLQo/jE4rsborFH5tB5vdwQ7DbLjipDaDchECaxty3kGlXuCIv8xgv8vWfMJwCoSptihfT+DwJgNGulQuiqheedsAFLUU4ZF+fLAo1nOIe3kFTnebJfbukjSBD2kEnDhiakUZS0LQQ1IRK60/XV3mFUGllsLq4g+LEs6kz71YB/8KtjYst6W78kSd9Qup83o1G+igIpQIdnbO/wPfKV8grfyuJOBRl77B6G+Gi5EmBf4pG92vXduMVDIce/foUYwD+gei
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflared-credentials
