apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - browserusemcp-pvc.yaml
  - browserusemcp-configmap.yaml
  - browserusemcp-deployment.yaml
  - browserusemcp-service.yaml

commonLabels:
  app.kubernetes.io/name: browserusemcp
  app.kubernetes.io/component: mcp-server

images:
  - name: browseruse/browseruse
    newTag: 0.12.9
