apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-cluster1.yaml
  - twentycrm-role.yaml
  - twentycrm-database.yaml
commonLabels:
  app: postgres-cluster
  managed-by: kustomize
