apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster1
spec:
  instances: 2
  bootstrap:
    initdb:
      database: mydb
      owner: postgres
  storage:
    size: 1Gi
  postgresql:
    parameters:
      shared_buffers: "64MB"
      effective_cache_size: "128MB"
    pg_hba:
      - host all all all trust