apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azp-agent-scaler
spec:
  scaleTargetRef:
    name: azp-agent
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: azure-pipelines
      metadata:
        poolName: "Default"
        targetPipelinesQueueLength: "1"
      authenticationRef:
        name: azp-agent-auth
